services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dtrack
      POSTGRES_USER: dtrack
      POSTGRES_PASSWORD: dtrack
    volumes:
      - dtrack_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dtrack"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dtrack-network

  dependency-track-apiserver:
    image: dependencytrack/apiserver:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ALPINE_DATABASE_MODE: external
      ALPINE_DATABASE_URL: jdbc:postgresql://postgres:5432/dtrack
      ALPINE_DATABASE_DRIVER: org.postgresql.Driver
      ALPINE_DATABASE_USERNAME: dtrack
      ALPINE_DATABASE_PASSWORD: dtrack
    ports:
      - "8081:8080"    # host:container
    volumes:
      - dtrack_apiserver_data:/data
    healthcheck:
      # use the apiserver /api/v1/version endpoint
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/api/v1/version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - dtrack-network

  dependency-track-frontend:
    image: dependencytrack/frontend:latest
    depends_on:
      - dependency-track-apiserver
    environment:
      API_BASE_URL: "http://dependency-track-apiserver:8080"
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dtrack-network

  jenkins-master:
    container_name: jenkins-master
    image: jenkins/jenkins:lts
    environment:
      - JENKINS_OPTS=-Djenkins.install.runSetupWizard=false
      # - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_URL=http://jenkins-master:8080
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - dtrack-network
    volumes:
      - jenkins_home_data:/var/jenkins_home
      - jenkins_plugins:/var/jenkins_home/plugins
    restart: always
    secrets:
      - admin_password

  jenkins-agent-1:
    container_name: jenkins-agent-1
    image: jenkins/inbound-agent
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_SECRET=hello-world-1234
      - JENKINS_AGENT_NAME=agent-1
    networks:
      - dtrack-network
    depends_on:
      - jenkins-master

  jenkins-agent-2:
    container_name: jenkins-agent-2
    image: jenkins/inbound-agent
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_SECRET=hello-world-1234
      - JENKINS_AGENT_NAME=agent-2
    networks:
      - dtrack-network
    depends_on:
      - jenkins-master

  jenkins-agent-3:
    container_name: jenkins-agent-3
    image: jenkins/inbound-agent
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_SECRET=hello-world-1234
      - JENKINS_AGENT_NAME=agent-3
    networks:
      - dtrack-network
    depends_on:
      - jenkins-master

secrets:
  admin_password:
    file: admin_password.txt

volumes:
  dtrack_postgres_data:
    # external: true
  dtrack_apiserver_data:
    # external: true
  jenkins_home_data:
    external: true
  jenkins_plugins:
    external: true

networks:
  dtrack-network:
    driver: bridge
